# SPDX-FileCopyrightText: 2022 Carnegie Mellon University
# SPDX-License-Identifier: 0BSD

name: python

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

env:
  PYTHONUNBUFFERED: 1

jobs:
  pre-commit:
    name: Rerun pre-commit checks
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up python
        uses: actions/setup-python@v4
      - name: Run pre-commit checks
        uses: pre-commit/action@v3.0.0
  tests:
    name: Tests
    needs: pre-commit
    strategy:
      matrix:
        python-version: [3.7, "3.10"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'
      - run: poetry install
      - run: poetry run pytest -v tests/
